name: .NET Core

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    branches: 
      - dev
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Build
      run: dotnet build --configuration Debug
      working-directory: ./client
    - name: test
      run: dotnet test
      env:
        TenantId: ${{secrets.TENANTID}}
        ClientId: ${{secrets.CLIENTID}}
        clientSecret: ${{secrets.CLIENTSECRET}}
      working-directory: ./client      
